export interface Lecture {
  id: number;
  title: string;
  instructor: string;
  category: string;
  level: 'beginner' | 'intermediate' | 'advanced';
  students: number;
  rating: number;
  duration: string;
  thumbnail: string;
  description: string;
  curriculum: {
    id: number;
    title: string;
    duration: string;
    completed?: boolean;
    current?: boolean;
  }[];
}

export const lectures: Lecture[] = [
  {
    id: 1,
    title: 'React Advanced Patterns',
    instructor: '김태희',
    category: 'frontend',
    level: 'advanced',
    students: 1234,
    rating: 4.8,
    duration: '8시간',
    thumbnail: 'https://images.unsplash.com/photo-1557324232-b8917d3c3dcb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3ZWIlMjBkZXZlbG9wbWVudCUyMGNvZGluZ3xlbnwxfHx8fDE3Njk4MzE0NjB8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    description: 'React의 고급 패턴과 Best Practice를 학습합니다. Custom Hooks, Compound Components, Render Props 등을 다룹니다.',
    curriculum: [
      { id: 1, title: 'Introduction to Advanced Patterns', duration: '12:30', completed: true },
      { id: 2, title: 'Understanding Custom Hooks', duration: '18:45', completed: true },
      { id: 3, title: 'Custom Hooks Best Practices', duration: '22:15', current: true },
      { id: 4, title: 'Compound Components Pattern', duration: '25:00' },
      { id: 5, title: 'Render Props vs Hooks', duration: '20:10' },
      { id: 6, title: 'Higher Order Components', duration: '19:30' },
      { id: 7, title: 'Context API Deep Dive', duration: '28:00' },
    ],
  },
  {
    id: 2,
    title: 'Next.js 완벽 가이드',
    instructor: '박지성',
    category: 'frontend',
    level: 'intermediate',
    students: 2156,
    rating: 4.9,
    duration: '12시간',
    thumbnail: 'https://images.unsplash.com/photo-1557324232-b8917d3c3dcb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3ZWIlMjBkZXZlbG9wbWVudCUyMGNvZGluZ3xlbnwxfHx8fDE3Njk4MzE0NjB8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    description: 'Next.js 14의 모든 기능을 마스터합니다. SSR, SSG, API Routes, App Router까지 완벽하게 학습합니다.',
    curriculum: [
      { id: 1, title: 'Next.js 시작하기', duration: '15:00' },
      { id: 2, title: 'Pages와 Routing', duration: '20:30' },
      { id: 3, title: 'Data Fetching 전략', duration: '25:45' },
      { id: 4, title: 'API Routes 구축', duration: '22:00' },
      { id: 5, title: 'App Router 심화', duration: '28:15' },
    ],
  },
  {
    id: 3,
    title: 'TypeScript 실전 프로젝트',
    instructor: '이민정',
    category: 'frontend',
    level: 'intermediate',
    students: 1876,
    rating: 4.7,
    duration: '10시간',
    thumbnail: 'https://images.unsplash.com/photo-1557324232-b8917d3c3dcb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3ZWIlMjBkZXZlbG9wbWVudCUyMGNvZGluZ3xlbnwxfHx8fDE3Njk4MzE0NjB8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    description: 'TypeScript로 실전 프로젝트를 진행하며 타입 시스템을 완벽하게 이해합니다.',
    curriculum: [
      { id: 1, title: 'TypeScript 기초', duration: '18:00' },
      { id: 2, title: 'Advanced Types', duration: '24:30' },
      { id: 3, title: 'Generics 마스터하기', duration: '20:45' },
      { id: 4, title: '실전 프로젝트', duration: '35:00' },
    ],
  },
  {
    id: 4,
    title: 'Node.js 백엔드 개발',
    instructor: '정우성',
    category: 'backend',
    level: 'intermediate',
    students: 1543,
    rating: 4.6,
    duration: '15시간',
    thumbnail: 'https://images.unsplash.com/photo-1565687981296-535f09db714e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiYWNrZW5kJTIwc2VydmVyJTIwY29kaW5nfGVufDF8fHx8MTc2OTgzODkzNHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    description: 'Node.js와 Express로 RESTful API를 구축하고 데이터베이스를 연동합니다.',
    curriculum: [
      { id: 1, title: 'Node.js 기초', duration: '16:00' },
      { id: 2, title: 'Express 프레임워크', duration: '22:30' },
      { id: 3, title: 'MongoDB 연동', duration: '25:45' },
      { id: 4, title: 'Authentication & Authorization', duration: '28:00' },
      { id: 5, title: 'API 배포하기', duration: '18:30' },
    ],
  },
  {
    id: 5,
    title: 'Python Django 마스터',
    instructor: '강호동',
    category: 'backend',
    level: 'beginner',
    students: 2341,
    rating: 4.8,
    duration: '14시간',
    thumbnail: 'https://images.unsplash.com/photo-1565687981296-535f09db714e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiYWNrZW5kJTIwc2VydmVyJTIwY29kaW5nfGVufDF8fHx8MTc2OTgzODkzNHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    description: 'Django로 풀스택 웹 애플리케이션을 개발합니다. ORM, Template, REST API를 학습합니다.',
    curriculum: [
      { id: 1, title: 'Django 시작하기', duration: '14:00' },
      { id: 2, title: 'Models와 ORM', duration: '26:30' },
      { id: 3, title: 'Views와 Templates', duration: '22:45' },
      { id: 4, title: 'Django REST Framework', duration: '30:00' },
    ],
  },
  {
    id: 6,
    title: '머신러닝 입문',
    instructor: '유재석',
    category: 'ai',
    level: 'beginner',
    students: 3124,
    rating: 4.9,
    duration: '20시간',
    thumbnail: 'https://images.unsplash.com/photo-1666875753105-c63a6f3bdc86?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkYXRhJTIwc2NpZW5jZSUyMGFuYWx5dGljc3xlbnwxfHx8fDE3Njk3MjkxNzl8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    description: 'Python으로 머신러닝의 기초부터 실전까지. Scikit-learn과 TensorFlow를 활용합니다.',
    curriculum: [
      { id: 1, title: '머신러닝 개요', duration: '18:00' },
      { id: 2, title: '데이터 전처리', duration: '24:30' },
      { id: 3, title: '지도 학습', duration: '28:45' },
      { id: 4, title: '비지도 학습', duration: '26:00' },
      { id: 5, title: '딥러닝 입문', duration: '32:15' },
    ],
  },
  {
    id: 7,
    title: 'Figma UI/UX 디자인',
    instructor: '송혜교',
    category: 'design',
    level: 'beginner',
    students: 2789,
    rating: 4.7,
    duration: '9시간',
    thumbnail: 'https://images.unsplash.com/photo-1618761714954-0b8cd0026356?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx1aSUyMHV4JTIwZGVzaWduJTIwaW50ZXJmYWNlfGVufDF8fHx8MTc2OTgyNTY2N3ww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    description: 'Figma를 활용한 모던 UI/UX 디자인. 실전 프로젝트로 포트폴리오를 완성합니다.',
    curriculum: [
      { id: 1, title: 'Figma 기초', duration: '12:00' },
      { id: 2, title: 'Component 시스템', duration: '18:30' },
      { id: 3, title: 'Prototype 만들기', duration: '20:45' },
      { id: 4, title: '디자인 시스템 구축', duration: '25:00' },
    ],
  },
  {
    id: 8,
    title: '모바일 앱 디자인',
    instructor: '전지현',
    category: 'design',
    level: 'intermediate',
    students: 1654,
    rating: 4.8,
    duration: '11시간',
    thumbnail: 'https://images.unsplash.com/photo-1618761714954-0b8cd0026356?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx1aSUyMHV4JTIwZGVzaWduJTIwaW50ZXJmYWNlfGVufDF8fHx8MTc2OTgyNTY2N3ww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    description: 'iOS와 Android 앱 디자인 가이드라인을 학습하고 실전 프로젝트를 진행합니다.',
    curriculum: [
      { id: 1, title: '모바일 디자인 기초', duration: '15:00' },
      { id: 2, title: 'iOS 디자인 가이드', duration: '22:30' },
      { id: 3, title: 'Android Material Design', duration: '20:45' },
      { id: 4, title: '실전 앱 디자인', duration: '28:00' },
    ],
  },
  {
    id: 9,
    title: '콘텐츠 글쓰기의 모든 것',
    instructor: '이외수',
    category: 'writing',
    level: 'beginner',
    students: 2987,
    rating: 4.9,
    duration: '10시간',
    thumbnail: 'https://images.unsplash.com/photo-1612907527100-f02bb2b26b1d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3cml0aW5nJTIwbm90ZWJvb2slMjBqb3VybmFsfGVufDF8fHx8MTc2OTc0NjE2Mnww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    description: '블로그, 뉴스레터, SNS 콘텐츠까지. 독자의 마음을 사로잡는 글쓰기 기술을 배웁니다.',
    curriculum: [
      { id: 1, title: '글쓰기 기본 원칙', duration: '14:00' },
      { id: 2, title: '매력적인 제목 만들기', duration: '18:30' },
      { id: 3, title: '스토리텔링 기법', duration: '22:45' },
      { id: 4, title: 'SEO 최적화 글쓰기', duration: '20:00' },
      { id: 5, title: '실전 콘텐츠 제작', duration: '25:15' },
    ],
  },
  {
    id: 10,
    title: '비즈니스 글쓰기 마스터',
    instructor: '김영하',
    category: 'writing',
    level: 'intermediate',
    students: 1876,
    rating: 4.7,
    duration: '8시간',
    thumbnail: 'https://images.unsplash.com/photo-1612907527100-f02bb2b26b1d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3cml0aW5nJTIwbm90ZWJvb2slMjBqb3VybmFsfGVufDF8fHx8MTc2OTc0NjE2Mnww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    description: '보고서, 이메일, 제안서 등 비즈니스 문서 작성의 핵심 노하우를 학습합니다.',
    curriculum: [
      { id: 1, title: '비즈니스 글쓰기 원칙', duration: '16:00' },
      { id: 2, title: '이메일 커뮤니케이션', duration: '20:30' },
      { id: 3, title: '설득력 있는 제안서', duration: '24:45' },
      { id: 4, title: '보고서 작성 실무', duration: '22:00' },
    ],
  },
  {
    id: 11,
    title: 'PM이 되기 위한 기획 입문',
    instructor: '김범수',
    category: 'planning',
    level: 'beginner',
    students: 3421,
    rating: 4.8,
    duration: '13시간',
    thumbnail: 'https://images.unsplash.com/photo-1760346546771-a81d986459ff?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxidXNpbmVzcyUyMHBsYW5uaW5nJTIwc3RyYXRlZ3l8ZW58MXx8fHwxNzY5Nzk1MzE0fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    description: '프로덕트 매니저가 되기 위한 기획의 기초부터 실전까지. 서비스 기획 전 과정을 학습합니다.',
    curriculum: [
      { id: 1, title: '기획자의 역할', duration: '15:00' },
      { id: 2, title: '시장 조사와 분석', duration: '22:30' },
      { id: 3, title: '사용자 리서치', duration: '26:45' },
      { id: 4, title: '와이어프레임 작성', duration: '20:00' },
      { id: 5, title: '기획서 작성 실무', duration: '28:15' },
    ],
  },
  {
    id: 12,
    title: '데이터 기반 서비스 기획',
    instructor: '배달의민족',
    category: 'planning',
    level: 'advanced',
    students: 2134,
    rating: 4.9,
    duration: '11시간',
    thumbnail: 'https://images.unsplash.com/photo-1760346546771-a81d986459ff?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxidXNpbmVzcyUyMHBsYW5uaW5nJTIwc3RyYXRlZ3l8ZW58MXx8fHwxNzY5Nzk1MzE0fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    description: 'Google Analytics, Mixpanel 등 데이터 분석 도구를 활용한 서비스 기획 방법론을 배웁니다.',
    curriculum: [
      { id: 1, title: '데이터 기획 개요', duration: '14:00' },
      { id: 2, title: 'GA4 활용 분석', duration: '25:30' },
      { id: 3, title: 'A/B 테스트 설계', duration: '22:45' },
      { id: 4, title: '지표 설정과 분석', duration: '26:00' },
      { id: 5, title: '실전 프로젝트', duration: '30:00' },
    ],
  },
  {
    id: 13,
    title: '린 스타트업 실전 가이드',
    instructor: '김봉진',
    category: 'startup',
    level: 'intermediate',
    students: 2765,
    rating: 4.8,
    duration: '16시간',
    thumbnail: 'https://images.unsplash.com/photo-1590097520505-416422f07ad1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdGFydHVwJTIwZW50cmVwcmVuZXVyJTIwb2ZmaWNlfGVufDF8fHx8MTc2OTgwNDI2MHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    description: '린 스타트업 방법론으로 빠르게 검증하고 성장하는 스타트업 만들기. MVP부터 PMF까지.',
    curriculum: [
      { id: 1, title: '린 스타트업 개론', duration: '18:00' },
      { id: 2, title: '문제-해결 핏 찾기', duration: '24:30' },
      { id: 3, title: 'MVP 개발 전략', duration: '28:45' },
      { id: 4, title: '고객 검증과 피봇', duration: '26:00' },
      { id: 5, title: 'Product-Market Fit', duration: '32:15' },
      { id: 6, title: '성장 전략', duration: '30:00' },
    ],
  },
  {
    id: 14,
    title: '스타트업 투자 유치 A to Z',
    instructor: '이태용',
    category: 'startup',
    level: 'advanced',
    students: 1923,
    rating: 4.7,
    duration: '12시간',
    thumbnail: 'https://images.unsplash.com/photo-1590097520505-416422f07ad1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdGFydHVwJTIwZW50cmVwcmVuZXVyJTIwb2ZmaWNlfGVufDF8fHx8MTc2OTgwNDI2MHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    description: 'Pre-Seed부터 Series A까지. 투자 유치 전략, 피칭 스킬, IR 자료 작성법을 배웁니다.',
    curriculum: [
      { id: 1, title: '스타트업 투자 생태계', duration: '16:00' },
      { id: 2, title: '투자 유치 준비', duration: '22:30' },
      { id: 3, title: '효과적인 피칭', duration: '25:45' },
      { id: 4, title: 'IR 덱 작성법', duration: '24:00' },
      { id: 5, title: '밸류에이션과 협상', duration: '28:30' },
    ],
  },
  {
    id: 15,
    title: 'IT 취업 완벽 대비',
    instructor: '원티드',
    category: 'career',
    level: 'beginner',
    students: 4235,
    rating: 4.9,
    duration: '14시간',
    thumbnail: 'https://images.unsplash.com/photo-1758518727653-5650fd9e146c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxqb2IlMjBpbnRlcnZpZXclMjBjYXJlZXIlMjBwcm9mZXNzaW9uYWx8ZW58MXx8fHwxNzY5ODM5Mzc4fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    description: '이력서 작성부터 면접 준비까지. IT 기업 취업을 위한 완벽한 준비 과정을 제공합니다.',
    curriculum: [
      { id: 1, title: 'IT 업계 이해하기', duration: '15:00' },
      { id: 2, title: '합격하는 이력서 작성', duration: '22:30' },
      { id: 3, title: '포트폴리오 구성', duration: '26:45' },
      { id: 4, title: '기술 면접 대비', duration: '28:00' },
      { id: 5, title: '인성 면접 준비', duration: '20:15' },
      { id: 6, title: '실전 모의 면접', duration: '24:30' },
    ],
  },
  {
    id: 16,
    title: '커리어 전환 전략',
    instructor: '박은빈',
    category: 'career',
    level: 'intermediate',
    students: 2345,
    rating: 4.8,
    duration: '10시간',
    thumbnail: 'https://images.unsplash.com/photo-1758518727653-5650fd9e146c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxqb2IlMjBpbnRlcnZpZXclMjBjYXJlZXIlMjBwcm9mZXNzaW9uYWx8ZW58MXx8fHwxNzY5ODM5Mzc4fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    description: '비전공자, 경력 전환자를 위한 체계적인 커리어 전환 로드맵과 실전 전략을 제공합니다.',
    curriculum: [
      { id: 1, title: '커리어 목표 설정', duration: '14:00' },
      { id: 2, title: '전환 가능 직무 탐색', duration: '18:30' },
      { id: 3, title: '스킬 갭 분석', duration: '22:45' },
      { id: 4, title: '학습 로드맵 수립', duration: '20:00' },
      { id: 5, title: '네트워킹 전략', duration: '25:15' },
    ],
  },
  {
    id: 17,
    title: '협업 커뮤니케이션 스킬',
    instructor: '조승우',
    category: 'career',
    level: 'beginner',
    students: 3124,
    rating: 4.7,
    duration: '8시간',
    thumbnail: 'https://images.unsplash.com/photo-1758518727653-5650fd9e146c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxqb2IlMjBpbnRlcnZpZXclMjBjYXJlZXIlMjBwcm9mZXNzaW9uYWx8ZW58MXx8fHwxNzY5ODM5Mzc4fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    description: '직장 내 효과적인 커뮤니케이션과 협업 노하우. 팀워크를 강화하고 업무 효율을 높입니다.',
    curriculum: [
      { id: 1, title: '커뮤니케이션 기본', duration: '12:00' },
      { id: 2, title: '피드백 주고받기', duration: '18:30' },
      { id: 3, title: '회의 효율화', duration: '20:45' },
      { id: 4, title: '갈등 관리', duration: '16:00' },
      { id: 5, title: '리더십 스킬', duration: '22:15' },
    ],
  },
  {
    id: 18,
    title: '서양 철학의 거장들',
    instructor: '최진석',
    category: 'humanities',
    level: 'beginner',
    students: 2456,
    rating: 4.9,
    duration: '16시간',
    thumbnail: 'https://images.unsplash.com/photo-1761319114925-6c29c745eac4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwaGlsb3NvcGh5JTIwYm9va3MlMjBsaWJyYXJ5JTIwaHVtYW5pdGllc3xlbnwxfHx8fDE3Njk4NDAyNTN8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    description: '소크라테스부터 니체까지. 서양 철학의 핵심 사상가들과 그들의 철학을 탐구합니다.',
    curriculum: [
      { id: 1, title: '고대 그리스 철학', duration: '20:00' },
      { id: 2, title: '중세 스콜라 철학', duration: '18:30' },
      { id: 3, title: '근대 합리론과 경험론', duration: '24:45' },
      { id: 4, title: '칸트와 독일 관념론', duration: '22:00' },
      { id: 5, title: '실존주의와 현대 철���', duration: '26:15' },
    ],
  },
  {
    id: 19,
    title: '동양 고전의 지혜',
    instructor: '김용옥',
    category: 'humanities',
    level: 'intermediate',
    students: 3187,
    rating: 4.8,
    duration: '14시간',
    thumbnail: 'https://images.unsplash.com/photo-1761319114925-6c29c745eac4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwaGlsb3NvcGh5JTIwYm9va3MlMjBsaWJyYXJ5JTIwaHVtYW5pdGllc3xlbnwxfHx8fDE3Njk4NDAyNTN8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    description: '논어, 맹자, 장자, 노자. 동양 고전에서 배우는 삶의 지혜와 리더십 철학을 학습합니다.',
    curriculum: [
      { id: 1, title: '논어 핵심 강독', duration: '22:00' },
      { id: 2, title: '맹자의 인간론', duration: '20:30' },
      { id: 3, title: '장자의 자유 철학', duration: '18:45' },
      { id: 4, title: '노자와 도덕경', duration: '24:00' },
      { id: 5, title: '현대 사회에의 적용', duration: '19:30' },
    ],
  },
  {
    id: 20,
    title: '역사로 읽는 인간 본성',
    instructor: '유발 하라리',
    category: 'humanities',
    level: 'advanced',
    students: 2871,
    rating: 4.9,
    duration: '18시간',
    thumbnail: 'https://images.unsplash.com/photo-1761319114925-6c29c745eac4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwaGlsb3NvcGh5JTIwYm9va3MlMjBsaWJyYXJ5JTIwaHVtYW5pdGllc3xlbnwxfHx8fDE3Njk4NDAyNTN8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    description: '사피엔스부터 호모 데우스까지. 인류 역사를 통해 인간의 본성과 미래를 탐구합니다.',
    curriculum: [
      { id: 1, title: '인지 혁명과 농업 혁명', duration: '24:00' },
      { id: 2, title: '제국과 종교의 탄생', duration: '22:30' },
      { id: 3, title: '과학 혁명과 자본주의', duration: '26:45' },
      { id: 4, title: '현대 문명의 딜레마', duration: '28:00' },
      { id: 5, title: '인간의 미래', duration: '30:15' },
    ],
  },
  {
    id: 21,
    title: '데미안 알아보기',
    instructor: '헤르만 헤세',
    category: 'humanities',
    level: 'beginner',
    students: 1842,
    rating: 4.8,
    duration: '9시간',
    thumbnail: 'https://images.unsplash.com/photo-1652711475965-61d2e00904e1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsaXRlcmF0dXJlJTIwYm9vayUyMHJlYWRpbmclMjBub3ZlbHxlbnwxfHx8fDE3Njk4NDAzNzN8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    description: '헤르만 헤세의 성장소설 데미안을 깊이 있게 분석합니다. 자아 찾기와 내면 성장의 여정을 함께 탐구합니다.',
    curriculum: [
      { id: 1, title: '데미안 작품 소개와 배경', duration: '15:00' },
      { id: 2, title: '두 개의 세계: 밝음과 어둠', duration: '18:30' },
      { id: 3, title: '데미안과의 만남', duration: '20:45' },
      { id: 4, title: '아브락사스 신화의 의미', duration: '22:00' },
      { id: 5, title: '자아 발견과 성장', duration: '19:15' },
    ],
  },
];

export const categories = [
  { id: 'all', name: '전체', icon: '📚' },
  { id: 'frontend', name: '프론트엔드', icon: '💻' },
  { id: 'backend', name: '백엔드', icon: '⚙️' },
  { id: 'ai', name: 'AI/ML', icon: '🤖' },
  { id: 'design', name: '디자인', icon: '🎨' },
  { id: 'writing', name: '글쓰기', icon: '✍️' },
  { id: 'planning', name: '기획', icon: '📋' },
  { id: 'startup', name: '창업', icon: '🚀' },
  { id: 'career', name: '취업역량', icon: '💼' },
  { id: 'humanities', name: '인문학', icon: '📖' },
];